[project]
name = "oim7510"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sinolax58", email = "along1@babson.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "marimo>=0.25.1",
]

[project.scripts]
oim7510 = "oim7510:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
